# Generated by Django 5.0.1 on 2024-01-22 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Actor", "0001_initial"),
        ("Movie", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="movies",
            field=models.ManyToManyField(
                blank=True, related_name="actor_movies", to="Movie.movie"
            ),
        ),
        migrations.AddField(
            model_name="actorvideo",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actors_video",
                to="Actor.actor",
            ),
        ),
    ]
