# Generated by Django 4.2.4 on 2023-12-27 10:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={},
        ),
        migrations.AlterModelManagers(
            name="account",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="account",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="account",
            name="email",
        ),
        migrations.RemoveField(
            model_name="account",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="account",
            name="last_name",
        ),
    ]
