# Generated by Django 5.0.1 on 2024-01-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_account_password"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="birth_date",
            new_name="birthday",
        ),
        migrations.RemoveField(
            model_name="account",
            name="username",
        ),
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
        migrations.AddField(
            model_name="account",
            name="email",
            field=models.EmailField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="account",
            name="password",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="account",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
