# Generated by Django 5.0.1 on 2024-01-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Account", "0002_alter_account_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
