# Generated by Django 5.0.1 on 2024-01-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Account", "0004_remove_account_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
