# Generated by Django 5.0.1 on 2024-02-21 18:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Account", "0006_account_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="name",
        ),
    ]
