# Generated by Django 5.0.1 on 2024-01-22 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Actor", "0001_initial"),
        ("Director", "0001_initial"),
        ("User", "0002_alter_user_bio_alter_user_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Action", "Action"),
                            ("Adventure", "Adventure"),
                            ("Animation", "Animation"),
                            ("Biography", "Biography"),
                            ("Comedy", "Comedy"),
                            ("Crime", "Crime"),
                            ("Documentary", "Documentary"),
                            ("Drama", "Drama"),
                            ("Family", "Family"),
                            ("Fantasy", "Fantasy"),
                            ("Film-Noir", "Film-Noir"),
                            ("History", "History"),
                            ("Horror", "Horror"),
                            ("Music", "Music"),
                            ("Musical", "Musical"),
                            ("Mystery", "Mystery"),
                            ("Romance", "Romance"),
                            ("Sci-Fi", "Sci-Fi"),
                            ("Sport", "Sport"),
                            ("Thriller", "Thriller"),
                            ("War", "War"),
                            ("Western", "Western"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("year", models.IntegerField()),
                ("image_url", models.CharField(blank=True, max_length=200, null=True)),
                ("duration", models.IntegerField()),
                (
                    "description",
                    models.CharField(blank=True, max_length=5000, null=True),
                ),
                ("summary", models.CharField(blank=True, max_length=2000, null=True)),
                (
                    "storyline",
                    models.TextField(blank=True, max_length=15000, null=True),
                ),
                (
                    "actors",
                    models.ManyToManyField(
                        related_name="movie_actors", to="Actor.actor"
                    ),
                ),
                (
                    "directors",
                    models.ManyToManyField(
                        related_name="movie_directors", to="Director.director"
                    ),
                ),
                (
                    "genres",
                    models.ManyToManyField(
                        related_name="movie_genre", to="Movie.genre"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="movieVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=200)),
                ("is_trailer", models.BooleanField(default=False)),
                ("duration", models.IntegerField()),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movie_video",
                        to="Movie.movie",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("comment", models.TextField(max_length=5000)),
                ("stars_rate", models.FloatField(default=0.0)),
                ("update_time", models.DateTimeField(auto_now_add=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movie_review",
                        to="Movie.movie",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_review",
                        to="User.user",
                    ),
                ),
            ],
        ),
    ]
