# Generated by Django 5.0.1 on 2024-01-03 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Actor", "0001_initial"),
        ("Director", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Action", 1),
                            ("Adventure", 2),
                            ("Animation", 3),
                            ("Biography", 4),
                            ("Comedy", 5),
                            ("Crime", 6),
                            ("Commercial", 7),
                            ("Documentary", 8),
                            ("Drama", 9),
                            ("Family", 10),
                            ("Fantasy", 11),
                            ("Film-Noir", 12),
                            ("History", 13),
                            ("Horror", 14),
                            ("Musical", 15),
                            ("Mystery", 16),
                            ("Romance", 17),
                            ("Sci-Fi", 18),
                            ("Sport", 19),
                            ("Thriller", 20),
                            ("War", 21),
                            ("Western", 22),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("year", models.IntegerField()),
                ("average_rating", models.FloatField(default=0.0)),
                ("description", models.CharField(max_length=200)),
                ("image_url", models.CharField(max_length=200)),
                ("duration", models.IntegerField()),
                ("storyline", models.CharField(max_length=300)),
                ("summary", models.CharField(max_length=500)),
                ("synopsis", models.TextField(max_length=20000)),
                (
                    "actors",
                    models.ManyToManyField(
                        related_name="movie_actors", to="Actor.actor"
                    ),
                ),
                (
                    "directors",
                    models.ManyToManyField(
                        related_name="movie_directors", to="Director.director"
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movie_genre",
                        to="Movie.genre",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="movieVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=200)),
                ("is_trailer", models.BooleanField(default=False)),
                ("duration", models.IntegerField()),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movie_video",
                        to="Movie.movie",
                    ),
                ),
            ],
        ),
    ]
