# Generated by Django 5.0.1 on 2024-01-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Movie", "0002_movie_ave_rating_alter_review_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="ave_rating",
            field=models.FloatField(default=0.0),
        ),
    ]
