# Generated by Django 4.2.4 on 2023-12-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movies",
            name="trailer_url",
        ),
        migrations.AddField(
            model_name="movievideo",
            name="is_trailer",
            field=models.BooleanField(default=False),
        ),
    ]
