# Generated by Django 5.0.1 on 2024-01-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_remove_movies_trailer_url_movievideo_is_trailer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movies",
            name="average_rating",
            field=models.FloatField(default=0.0),
        ),
    ]
