# Generated by Django 4.2.4 on 2023-12-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("movies", "0001_initial"),
        ("directors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="director",
            name="movies",
            field=models.ManyToManyField(
                related_name="director_movies", to="movies.movies"
            ),
        ),
    ]
