# Generated by Django 5.0.1 on 2024-01-08 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Director", "0001_initial"),
        ("Movie", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="director",
            name="movies",
            field=models.ManyToManyField(
                blank=True, related_name="director_movies", to="Movie.movie"
            ),
        ),
        migrations.AddField(
            model_name="directorvideo",
            name="director",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="director_video",
                to="Director.director",
            ),
        ),
    ]
