# Generated by Django 4.2.4 on 2023-12-27 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("movies", "0001_initial"),
        ("actors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.movies",
            ),
        ),
        migrations.AddField(
            model_name="actor",
            name="movies",
            field=models.ManyToManyField(
                related_name="actor_movies", to="movies.movies"
            ),
        ),
        migrations.AddField(
            model_name="actor",
            name="video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="actors.actorvideo",
            ),
        ),
    ]
