# Generated by Django 4.2.4 on 2023-12-27 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("actors", "0001_initial"),
        ("directors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Action", "Action"),
                            ("Adventure", "Adventure"),
                            ("Animation", "Animation"),
                            ("Biography", "Biography"),
                            ("Comedy", "Comedy"),
                            ("Crime", "Crime"),
                            ("Commercial", "Commercial"),
                            ("Documentary", "Documentary"),
                            ("Drama", "Drama"),
                            ("Family", "Family"),
                            ("Fantasy", "Fantasy"),
                            ("Film-Noir", "Film-Noir"),
                            ("History", "History"),
                            ("Horror", "Horror"),
                            ("Music", "Music"),
                            ("Musical", "Musical"),
                            ("Mystery", "Mystery"),
                            ("Romance", "Romance"),
                            ("Sci-Fi", "Sci-Fi"),
                            ("Sport", "Sport"),
                            ("Thriller", "Thriller"),
                            ("War", "War"),
                            ("Western", "Western"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Movies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("year", models.IntegerField()),
                ("average_rating", models.FloatField()),
                ("description", models.CharField(max_length=200)),
                ("image_url", models.CharField(max_length=200)),
                ("trailer_url", models.CharField(max_length=200)),
                ("duration", models.IntegerField()),
                ("storyline", models.CharField(max_length=300)),
                ("summary", models.CharField(max_length=500)),
                ("synopsis", models.TextField(max_length=20000)),
                (
                    "actors",
                    models.ManyToManyField(
                        related_name="movie_actors", to="actors.actor"
                    ),
                ),
                (
                    "directors",
                    models.ManyToManyField(
                        related_name="movie_directors", to="directors.director"
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movie_genre",
                        to="movies.genre",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="movieVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=200)),
                ("duration", models.IntegerField()),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movie_video",
                        to="movies.movies",
                    ),
                ),
            ],
        ),
    ]
